# Generated by Django 2.2.1 on 2019-05-15 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notandi', '0002_auto_20190515_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileImage',
        ),
    ]
