# Generated by Django 2.2.1 on 2019-05-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteignasala', '0003_auto_20190509_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='estimated_value',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='fire_insurance',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_bath_room',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_bed_room',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_rooms',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='size',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='zip',
            field=models.IntegerField(max_length=3),
        ),
    ]
