# Generated by Django 2.2.1 on 2019-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('card_number', models.CharField(max_length=16)),
                ('ccv', models.CharField(max_length=3)),
                ('date_of_expiration', models.DateField(max_length=8)),
                ('street_name', models.CharField(max_length=50)),
                ('house_num', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('ssn', models.CharField(max_length=10)),
            ],
        ),
    ]
