# Generated by Django 2.2.1 on 2019-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ssn', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('pay_name', models.CharField(max_length=60)),
                ('card_number', models.CharField(max_length=16)),
                ('date_of_expiration', models.DateField(max_length=8)),
                ('ccv', models.CharField(max_length=3)),
            ],
        ),
    ]
