# Generated by Django 2.2.1 on 2019-05-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greidsla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='city',
        ),
    ]
