# Generated by Django 2.2.1 on 2019-05-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greidsla', '0002_remove_buyer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='ssn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
