# Generated by Django 2.2.1 on 2019-05-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasteignasala', '0005_auto_20190514_1537'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='apartment',
        ),
        migrations.AddField(
            model_name='history',
            name='apartment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fasteignasala.Apartment'),
            preserve_default=False,
        ),
    ]
